# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: flywayCliInstall@0
  inputs:
    flywayVersion: '10.17.0'

- task: CmdLine@2
  inputs:
    script: 'flyway migrate -X'
  env:
    FLYWAY_PUBLISH_RESULT: "true"
    FLYWAY_EMAIL: "mikiel.agutu@red-gate.com"
    FLYWAY_TOKEN: "$(flyway_token)"