[environments.main]
url = "jdbc:h2:mem:some_db"
displayName = "Development database"

[flyway]
environment = "main"
locations = ["filesystem:./sql"]

[ flyway.flywayServicePublish ]
baseUri = "https://flywayservice-main.redgate-testing.com"