name = "Halcyon DB"

[environments.prod]
url = "jdbc:h2:mem:some_db"
displayName = "Development database"

[environments.qa]
url = "jdbc:h2:mem:some_db"
displayName = "Development database"

[flyway]
locations = ["filesystem:./sql"]

[ flyway.flywayServicePublish ]
baseUri = "https://flywayservice-main.redgate-testing.com/api"